name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check:
    runs-on: docker
    container:
      image: rust:1.97-bookworm

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install clippy and rustfmt
        run: rustup component add clippy rustfmt
      - name: Formatting
        run: cargo fmt --check
      - name: Clippy
        run: cargo clippy --all-targets -- -F clippy::missing_docs_in_private_items -D warnings
      - name: Build
        run: cargo build --all-targets
      - name: Test
        run: cargo test
      - name: Docs
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --no-deps --document-private-items
