name: Compile and test 
run-name: Building and testing commit `{{ github.sha }}`...

on: push

jobs:
  lint:
    name: Lint with Clippy
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable

      - name: Lint
        run: cargo clippy

  compile:
    name: Compile with Cargo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable

      - name: Compile
        run: cargo check

  test:
    name: Run unit tests
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        rust:
          - stable
          - beta
          - nightly
    runs-on: ${{ matrix.os }}
    needs: [ compile ]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: ${{ matrix.rust }}

      - name: Test
        run: cargo test

